### ISSUE TITLE
Bug: the server responded with a status of 502 uploadApk:1 in Docker

### ISSUE THREAD

**Issue by mlshdev** [inotia00/rvx-builder#155]
**Describe the bug**
the server responded with a status of 502 uploadApk:1 

**To Reproduce**
1. Build docker image
2. docker compose up rvx -d 
3. Reverse proxy it with traefik
4. Try to upload app (I used tiktok 36.5.4)
5. Go to chrome devtools and check errors
6. "the server responded with a status of 502 uploadApk:1"

**rvx-builder Version:** [e.g. v3.11.1]
v3.16.1

- OS: 6.1.0-26-amd64 Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

Docker container logs does not show any errors
docker-compose.yml
``` 
rvx:
    image: rvx:latest
    container_name: rvx
    networks:
      - proxy
    volumes:
      - ./rvx:/app/rvx-builder/revanced/
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rvx.rule=Host(`X`)"
      - "traefik.http.routers.rvx.entrypoints=websecure"
      - "traefik.http.routers.rvx.service=rvx"
      - "traefik.http.routers.rvx.tls=true"
      - "traefik.http.routers.rvx.middlewares=default@file"
      - "traefik.http.services.rvx.loadbalancer.server.port=8000"
```
